Setup mobile skeleton
dd-obua/Portfolio pull request #2
Opened 2022-02-17 11:17 UTC by dd-obua

# In this project (Portfolio: setup and mobile version skeleton), I have:
- Written an HTML file to convert a design in Figma to a web page and
- Styled it using CSS to mimic the appearance of the design.

2022-02-17 13:26 UTC, gemmen29 requested changes
Hi @dd-obua, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 13:26 UTC, gemmen29 commented on index.html
> +        </div>
Please wrap this part with a `nav` tag for semantic purposes so it will be like:
```
<header>
   <nav>
       (the content)
   </nav>
</header>
```

2022-02-17 13:26 UTC, gemmen29 commented on index.html
> +      </header>
Kindly add ` align-items: center ` for the header. also try to match the Figma design in top and button spacing for the header

2022-02-17 13:26 UTC, gemmen29 commented on index.html
> +      </main>
Kindly change the `main` tag to the `section` tag for semantic purposes.

2022-02-17 13:26 UTC, gemmen29 commented on index.html
> +          <h4 id="name">Hey there. I'm Denis</h4>
Please change the `h4` to be `h1` since it's the main heading on the page

2022-02-18 06:54 UTC, AkashaRojee approved these changes
Hi @dd-obua,

Great job on implementing the changes requested for your portfolio setup 😃 

Your project is complete! You can now proceed to merge it.

Congratulations! 🎉 

**_Note:_** There are some project requirements that the previous reviewer didn't include in the last review. Sorry about that. I have included them below so that you know what you missed.

  But don't worry 😉 Since the previous reviewer did not point them out, they will be marked as optional in this review.

  Please, keep in mind that the optional suggestions are there to help you improve and become an even better developer 🌟 🌟 🌟 🌟 🌟 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-18 08:01 UTC, merged